#nullable enable
using System;
using System.Windows.Forms;

namespace AutoRetard;

internal static class Program
{
    [STAThread]
    private static void Main()
    {
        // Sets up visual styles, default font and high-DPI mode (generated by the WinForms SDK).
        ApplicationConfiguration.Initialize();
        Application.Run(new MainForm());
    }
}